name: Android CI with Coverage

on:
  workflow_run:
    workflows: ["Android unit tests"]
    types:
      - completed

jobs:
  report-coverage:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
    
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Unit Tests with Coverage
      run: ./gradlew jacocoTestReport

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true

    - name: Push Badge to Branch
      if: github.event.workflow_run.head_branch == 'main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: badges
        folder: badges
        clean: false

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: app/build/reports/jacoco/jacocoTestReport/html/
